---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  annotations:  
    cert-manager.io/inject-ca-from: default/my-selfsigned-ca
webhooks:
  - name: mutating-webhook-service.default.svc.cluster.local
    objectSelector:
      matchLabels:
        gcp-sql-proxy: enabled
    failurePolicy: Fail
    clientConfig:
      service:
        name: mutating-webhook-service
        namespace: default
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
