apiVersion: v1
data:
  INSTANCE: -instances=od-io-development:europe-west4:development-mysql-master=tcp:3306
kind: ConfigMap
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: test
  namespace: default
---
apiVersion: v1
data:
  INSTANCE: -instances=od-io-staging:europe-west4:development-mysql-master=tcp:3306
kind: ConfigMap
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: test2
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: mutating-webhook-service
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    component: mutating-webhook-server
    od.io/overlay: base
    od.io/provisioner: kustomize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: mutating-webhook-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mutating-webhook-server
      od.io/overlay: base
      od.io/provisioner: kustomize
  template:
    metadata:
      labels:
        component: mutating-webhook-server
        od.io/overlay: base
        od.io/provisioner: kustomize
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: root-secret
        image: smithaj/sidecar:1.04
        imagePullPolicy: Never
        name: mutating-webhook-server
        volumeMounts:
        - mountPath: certs
          name: certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: my-selfsigned-ca
  namespace: default
spec:
  commonName: mutating-webhook-service.default.svc
  dnsNames:
  - mutating-webhook-service.default.svc
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: my-ca-issuer
  namespace: default
spec:
  ca:
    secretName: root-secret
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: default/my-selfsigned-ca
  labels:
    od.io/overlay: base
    od.io/provisioner: kustomize
  name: mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: mutating-webhook-service
      namespace: default
      path: /mutate
  failurePolicy: Fail
  name: mutating-webhook-service.default.svc.cluster.local
  objectSelector:
    matchLabels:
      gcp-sql-proxy: enabled
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
