---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  od.io/provisioner: kustomize
  od.io/overlay: base

resources:
  - admission.yaml
  - deployment.yaml
  - service.yaml
