---
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test
      gcp-sql-proxy: enabled
  template:
    metadata:
      annotations:
       # sqlinstance: -instances=project:region:instance-name=tcp:port
      labels:
        component: test
        foo: bar
        gcp-sql-proxy: enabled
    spec:
      containers:
      - name: test
        image: node:14-alpine
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
